### ISSUE TITLE
Login/Sign Up frontend

### ISSUE THREAD

**Issue by Mzon2857** [Hack-Weekly/bronze-badger-banking-app#1]

**Comment by Mcutrer5** [comment]
![firefox_2023-10-21_00-43-33](https://github.com/Hack-Weekly/bronze-badger-banking-app/assets/60704217/7db723e9-29c6-47f3-bc44-971fefffe4f7)
![firefox_2023-10-21_00-43-46](https://github.com/Hack-Weekly/bronze-badger-banking-app/assets/60704217/5efcff12-160a-433d-9fee-d4d4ac6d2d5e)
